export * from 'react-icons/fa';
export * from 'react-icons/fi';
export * from 'react-icons/bs';
export * from 'react-icons/ai';
export * from 'react-icons/si';
export * from 'react-icons/vsc';
export * from 'react-icons/io';
export * from 'react-icons/hi';
export * from 'react-icons/tb';
